---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: platform-service.k8s.io
spec:
  group: platform.k8s.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                  required: true
                uid:
                  type: string
                  required: true
                description:
                  type: string
            status:
              type: object
  names:
    kind: PlatformService
    plural: platformservices
  scope: Namespaced