---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: platform.k8s.io
spec:
  group: platform.k8s.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                services:
                  type: object
                  properties:
                    uid:
                      type: string
                      required: true
            status:
              type: object
  names:
    kind: Platform
    plural: platforms
  scope: Cluster